[FIX] l10n_it_central_journal_reportlab, lines without account or without entry name
We must exclude lines without account (like notes in invoice lines) because they are not significant for central journal;
otherwise:
l10n_it_central_journal_reportlab/wizard/print_giornale.py", line 471, in get_final_tables_report_giornale
    else line["account_name"][user_lang]
         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

Also, lines without name (like draft invoices) must be printed without error. But default behaviour should be printing posted entries