index on 8.0_imp_comunicazione_dati_iva: 3141f610 [ADD] icon.png
index on 8.0_imp_comunicazione_dati_iva: 2edfea1b WIP on 8.0_imp_comunicazione_dati_iva: 3141f610 [ADD] icon.png

[8.0] port

[8.0] port

FIX l10n_it_fatturapa_out_ddt to make it compatible with delivery module.

Otherwise

ERROR: test_e_invoice_ddt (odoo.addons.l10n_it_fatturapa_out_ddt.tests.test_fatturapa_ddt.TestInvoiceDDT)
Traceback (most recent call last):
`   File "/home/travis/build/eLBati/l10n-italy/l10n_it_fatturapa_out_ddt/tests/test_fatturapa_ddt.py", line 58, in test_e_invoice_ddt
`     (self.so1.picking_ids | self.so2.picking_ids).do_transfer()
`   File "/home/travis/odoo-10.0/addons/delivery/models/stock_picking.py", line 113, in do_transfer
`     self.ensure_one()
`   File "/home/travis/odoo-10.0/odoo/models.py", line 4859, in ensure_one
`     raise ValueError("Expected singleton: %s" % self)
` ValueError: Expected singleton: stock.picking(42, 43)

[FIX] fields

[IMP] fix fields and tax group function

[WIP] better dict computation

[FIX] add checks and currency

[FIX] invoice supplier number

[FIX] add missing fields from other module not in l10n-italy